# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_caesarCipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_caesarCipher.setGeometry(QtCore.QRect(180, 30, 311, 41))
        font = QtGui.QFont()
        font.setFamily(".VnArial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_caesarCipher.setFont(font)
        self.lbl_caesarCipher.setObjectName("lbl_caesarCipher")
        self.lbl_plainText = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plainText.setGeometry(QtCore.QRect(40, 120, 61, 21))
        self.lbl_plainText.setObjectName("lbl_plainText")
        self.lbl_cipherText = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipherText.setGeometry(QtCore.QRect(40, 280, 61, 21))
        self.lbl_cipherText.setObjectName("lbl_cipherText")
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setGeometry(QtCore.QRect(40, 230, 47, 13))
        self.lbl_key.setObjectName("lbl_key")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(430, 410, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(130, 410, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.txt_plainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plainText.setGeometry(QtCore.QRect(120, 130, 381, 81))
        self.txt_plainText.setObjectName("txt_plainText")
        self.txt_cipherText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipherText.setGeometry(QtCore.QRect(120, 290, 381, 81))
        self.txt_cipherText.setObjectName("txt_cipherText")
        self.txt_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(120, 230, 381, 31))
        self.txt_key.setObjectName("txt_key")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_caesarCipher.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_plainText.setText(_translate("MainWindow", "Plain Text:"))
        self.lbl_cipherText.setText(_translate("MainWindow", "Cipher Text:"))
        self.lbl_key.setText(_translate("MainWindow", "Key:"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
